### ISSUE TITLE
18. As a user, I would like to have a clear indicator of items purchased

### ISSUE THREAD

**Issue by veeteeran** [the-collab-lab/tcl-17-smart-shopping-list#43]
Use round checkboxes similar to iOS devices 

Styling radio buttons as [checkboxes](https://material-ui.com/components/checkboxes/) using [Material UI](https://material-ui.com/components/checkboxes/)

AC:

* Checkboxes should be empty when the item has not been purchased
* Checkboxes should be clearly marked when the item has been purchased

**Comment by chrisdopuch** [comment]
I love using Material UI, that's what I built my personal site with 👍
